# required configuration options
name: Docker Proxy
version: v0.4.1
slug: docker-proxy
description: 	Proxy over your Docker socket to restrict which requests it accepts
arch:
  - amd64

# Esta línea deshabilita la inicialización por defecto y nos permite usar 'cmd' y 'host_pid: true'
init: false 

# VOLÚMENES Y PERMISOS: La combinación que debería resolver el acceso
# 1. Acceso de bajo nivel al host (más permisivo)
host_pid: true
hassio_api: true
auth_api: true
docker_api: true
host_network: true
apparmor: false
# homepage of the add-on
url: "https://github.com/Adribreezy/breeznas-addons-homeassistant"
environment:
  DOCKER_HOST: unix:///run/docker.sock
  LOG_LEVEL: "info" 
  EVENTS: "1"
  PING: "1"
  VERSION: "1"
  AUTH: "0"
  SECRETS: "0"
  POST: "1" 
  BUILD: "0"
  COMMIT: "0"
  CONFIGS: "0"
  CONTAINERS: "1" 
  DISTRIBUTION: "0"
  EXEC: "0"
  IMAGES: "1"
  INFO: "1"
  NETWORKS: "1"
  NODES: "0"
  PLUGINS: "0"
  SERVICES: "1"
  SESSION: "0"
  SWARM: "0"
  SYSTEM: "0"
  TASKS: "1"
  VOLUMES: "1"
panel_icon: mdi:atom
panel_admin: false
panel_title: docker Proxy
startup: services
ports:
  2375/tcp: 2375
ports_description:
  2375/tcp: Proxy Expose
# La imagen base (versión sin etiqueta implica ':latest', pero es mejor ser explícito con una versión si es posible)
image: tecnativa/docker-socket-proxy